name: Backend Build and Deploy

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  build-and-deploy-backend:
    name: Build and Deploy Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build Backend
        run: ./gradlew clean build -x test
        working-directory: backend/demo

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./backend/demo
          push: true
          tags: ghcr.io/davormucak/voloconnect/backend:latest

      - name: Trigger Backend Redeploy
        if: ${{ secrets.BACKEND_DEPLOY_HOOK }}
        run: curl -X POST ${{ secrets.BACKEND_DEPLOY_HOOK }}
