name: Build and Push Backend Image

on:
  push:
    branches:
      - dev                 # Promijenjeno s 'master' na 'dev'
    paths:
      - 'backend/**'        # Pokreće se samo na promjene u /backend direktoriju
  workflow_dispatch:

jobs:
  build-and-push-backend:
    name: Build and Push Backend
    runs-on: ubuntu-latest
    env:
      BACKEND_DEPLOY_HOOK: ${{ secrets.BACKEND_DEPLOY_HOOK }}

    steps:
      - name: Clone the repository
        uses: actions/checkout@v4

      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
          cache: 'gradle'
          cache-dependency-path: 'backend/gradle.properties'  # Zamijenjeno s cache-om za Gradle

      - name: Gradle build                     # Zamijenjeno za Gradle
        run: ./gradlew build
        working-directory: backend

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
