name: Frontend Build and Deploy

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  build-and-deploy-frontend:
    name: Build and Deploy Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies and Build Frontend
        run: |
          npm install
          npm run build
        working-directory: frontend

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: ghcr.io/davormucak/voloconnect/frontend:latest

      - name: Trigger Frontend Redeploy
        if: ${{ secrets.FRONTEND_DEPLOY_HOOK }}
        run: curl -X POST ${{ secrets.FRONTEND_DEPLOY_HOOK }}
